language: php

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: SNIFF=1
    - php: "nightly"

  fast_finish: true

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p php tests
  - ./parallel-lint --exclude vendor --exclude tests/examples --no-colors .
  - ./parallel-lint --exclude vendor --exclude tests/examples .
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpcs;fi
