name: Build and test phar

on:
  push:
    tags:
      - 'v*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    # Don't run on forks.
    if: github.repository == 'php-parallel-lint/PHP-Parallel-Lint'

    name: Build binary
    uses: ./.github/workflows/reusable-build-binary.yml
    with:
      use-cache: false

  verify:
    name: Validate binary on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php == '8.6' }}
    needs:
      - bundle

    strategy:
      matrix:
        php:
          - '5.3'
          - '5.4'
          - '5.5'
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
          - '8.6'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download PHAR file
        uses: actions/download-artifact@v8
        with:
          name: parallel-lint-phar

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, display_startup_errors=On, zend.assertions=1
          coverage: none

      - name: Run linter against codebase
        run: php ./parallel-lint.phar src/

  publish:
    name: Add binary to release
    runs-on: ubuntu-latest
    needs:
      - bundle
      - verify

    steps:
      - name: Download PHAR file
        uses: actions/download-artifact@v8
        with:
          name: parallel-lint-phar

      - name: Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          make_latest: true
          files: parallel-lint.phar
          fail_on_unmatched_files: true
